
services:
  dev:
    build: .
    container_name: geopackage-dev
    volumes:
      - .:/workspace  # Mount current directory into the container
    ports:
      - "8080:8080"   # For JupyterLab (optional)
      - "2222:22"     # For SSH if needed (optional)
    environment:
      - DATABASE_TYPE=geopackage
      - GEOPACKAGE_PATH=/workspace/data/metadata.gpkg
    tty: true         # Keep the container running