services:
  postgres:
    image: postgis/postgis:17-3.5  # PostGIS-enabled image
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persistent storage for PostgreSQL data
    ports:
      - "${POSTGRES_PORT}:5432"  # Expose PostgreSQL port to the host
volumes:
  pgdata: