
services:
  dev:
    build: .
    container_name: geopackage-dev
    volumes:
      - .:/workspace  # Mount current directory into the container
      - ${DATA_FOLDER}:/data  # Mount the external folder to the internal folder
    ports:
      - "8080:8888"   
      - "5000:5000"   
      - "2222:22"    
    environment:
      - RUNNING_IN_DOCKER=true  # Environment variable to detect Docker
    tty: true         # Keep the container running